# GENERATED by live/scripts/generate-stacks.py from inventory.yaml.
# Do not edit by hand — edit inventory.yaml and re-run the generator.

unit "prod-1-us-east-1" {
  source = "../../units/ara-region"
  path   = "prod-1/us-east-1"
  values = {
    account_name        = "prod-1"
    account_id          = "333333333333"
    region              = "us-east-1"
    aws_profile         = ""
    deployer_role_arn   = "arn:aws:iam::333333333333:role/tec-deployer"
    unit_name           = "prod-1-us-east-1"
    create_target_roles = false
    target_roles        = {
      readonly  = {
        name = "ReadOnly"
      }
      poweruser = {
        name = "PowerUser"
      }
      admin     = {
        name = "Admin"
      }
    }
  }
}

unit "prod-1-us-west-2" {
  source = "../../units/ara-region"
  path   = "prod-1/us-west-2"
  values = {
    account_name        = "prod-1"
    account_id          = "333333333333"
    region              = "us-west-2"
    aws_profile         = ""
    deployer_role_arn   = "arn:aws:iam::333333333333:role/tec-deployer"
    unit_name           = "prod-1-us-west-2"
    create_target_roles = false
    target_roles        = {
      readonly  = {
        name = "ReadOnly"
      }
      poweruser = {
        name = "PowerUser"
      }
      admin     = {
        name = "Admin"
      }
    }
  }
}

unit "prod-1-eu-west-1" {
  source = "../../units/ara-region"
  path   = "prod-1/eu-west-1"
  values = {
    account_name        = "prod-1"
    account_id          = "333333333333"
    region              = "eu-west-1"
    aws_profile         = ""
    deployer_role_arn   = "arn:aws:iam::333333333333:role/tec-deployer"
    unit_name           = "prod-1-eu-west-1"
    create_target_roles = false
    target_roles        = {
      readonly  = {
        name = "ReadOnly"
      }
      poweruser = {
        name = "PowerUser"
      }
      admin     = {
        name = "Admin"
      }
    }
  }
}
