# GENERATED by live/scripts/generate-stacks.py from inventory.yaml.
# Do not edit by hand — edit inventory.yaml and re-run the generator.

unit "test-1-us-east-1" {
  source = "../../units/ara-region"
  path   = "test-1/us-east-1"
  values = {
    account_name        = "test-1"
    account_id          = "111111111111"
    region              = "us-east-1"
    aws_profile         = "teleport-test-1"
    deployer_role_arn   = ""
    unit_name           = "test-1-us-east-1"
    create_target_roles = true
    target_roles        = {
      readonly  = {
        name                = "ReadOnly"
        managed_policy_arns = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
      }
      poweruser = {
        name                = "PowerUser"
        managed_policy_arns = ["arn:aws:iam::aws:policy/PowerUserAccess"]
      }
      admin     = {
        name                = "Admin"
        managed_policy_arns = ["arn:aws:iam::aws:policy/AdministratorAccess"]
      }
    }
    roles_unit_path     = ""
  }
}

unit "test-1-us-west-2" {
  source = "../../units/ara-region"
  path   = "test-1/us-west-2"
  values = {
    account_name        = "test-1"
    account_id          = "111111111111"
    region              = "us-west-2"
    aws_profile         = "teleport-test-1"
    deployer_role_arn   = ""
    unit_name           = "test-1-us-west-2"
    create_target_roles = false
    target_roles        = {
      readonly  = {
        name = "ReadOnly"
      }
      poweruser = {
        name = "PowerUser"
      }
      admin     = {
        name = "Admin"
      }
    }
    roles_unit_path     = "../us-east-1"
  }
}

unit "test-2-us-east-1" {
  source = "../../units/ara-region"
  path   = "test-2/us-east-1"
  values = {
    account_name        = "test-2"
    account_id          = "222222222222"
    region              = "us-east-1"
    aws_profile         = "teleport-test-2"
    deployer_role_arn   = ""
    unit_name           = "test-2-us-east-1"
    create_target_roles = true
    target_roles        = {
      readonly  = {
        name                = "ReadOnly"
        managed_policy_arns = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
      }
      poweruser = {
        name                = "PowerUser"
        managed_policy_arns = ["arn:aws:iam::aws:policy/PowerUserAccess"]
      }
      admin     = {
        name                = "Admin"
        managed_policy_arns = ["arn:aws:iam::aws:policy/AdministratorAccess"]
      }
    }
    roles_unit_path     = ""
  }
}

unit "test-2-us-west-2" {
  source = "../../units/ara-region"
  path   = "test-2/us-west-2"
  values = {
    account_name        = "test-2"
    account_id          = "222222222222"
    region              = "us-west-2"
    aws_profile         = "teleport-test-2"
    deployer_role_arn   = ""
    unit_name           = "test-2-us-west-2"
    create_target_roles = false
    target_roles        = {
      readonly  = {
        name = "ReadOnly"
      }
      poweruser = {
        name = "PowerUser"
      }
      admin     = {
        name = "Admin"
      }
    }
    roles_unit_path     = "../us-east-1"
  }
}
