#!/usr/bin/env python3
"""Generate Terragrunt stack files from inventory.yaml.

Terragrunt units do not yet support for_each/count (gruntwork-io/terragrunt#4504),
so we generate the explicit `unit` blocks instead. For each environment this
writes live/<env>/terragrunt.stack.hcl with one unit per account/region.

Usage:  python3 live/scripts/generate-stacks.py
Run it after editing inventory.yaml, and commit both.
"""
import os
import yaml

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INVENTORY = os.path.join(REPO, "live", "inventory.yaml")


def to_hcl(v, indent=0):
    """Render a Python value as HCL (strings, bools, numbers, lists, dicts)."""
    pad = "  " * indent
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return '"' + v.replace('"', '\\"') + '"'
    if isinstance(v, list):
        return "[" + ", ".join(to_hcl(x, indent) for x in v) + "]" if v else "[]"
    if isinstance(v, dict):
        if not v:
            return "{}"
        inner = "  " * (indent + 1)
        width = max(len(k) for k in v)
        lines = [f"{inner}{k.ljust(width)} = {to_hcl(val, indent + 1)}" for k, val in v.items()]
        return "{\n" + "\n".join(lines) + "\n" + pad + "}"
    raise TypeError(f"cannot render {type(v)} as HCL")


def resolve(account, env, defaults, key, fallback=None):
    """account override → environment override → defaults → fallback."""
    if key in account:
        return account[key]
    if key in env:
        return env[key]
    return defaults.get(key, fallback)


def target_roles(roles, create):
    """Map access_level => { name, [managed_policy_arns] }. Policies only matter
    when creating, so they're omitted from the referenced (prod) case."""
    out = {}
    for level, spec in roles.items():
        entry = {"name": spec["name"]}
        if create and spec.get("managed_policy_arns"):
            entry["managed_policy_arns"] = spec["managed_policy_arns"]
        out[level] = entry
    return out


def render_unit(u):
    return f'''unit "{u["unit_name"]}" {{
  source = "../../units/ara-region"
  path   = "{u["account_name"]}/{u["region"]}"
  values = {to_hcl(u["values"], 1)}
}}'''


def main():
    with open(INVENTORY) as f:
        inv = yaml.safe_load(f)

    defaults = inv.get("defaults", {})

    for env_name, env in inv["environments"].items():
        units = []
        for acct in env["accounts"]:
            account_id = str(acct["account_id"])
            regions = resolve(acct, env, defaults, "regions", [])
            roles = resolve(acct, env, defaults, "roles", {})
            create = bool(resolve(acct, env, defaults, "create_roles", False))

            # IAM roles are GLOBAL, so when an account creates them we do it in
            # exactly ONE region (the first) and reference that same role from
            # the others — otherwise both region units would create the same
            # role name and collide. The referencing regions declare an ordering
            # dependency on the creator so the role exists before their Roles
            # Anywhere profiles point at it. (When create=false, every region
            # references pre-existing roles, so there's no creator/dependency.)
            creator_region = regions[0] if (create and regions) else None
            for region in regions:
                is_creator = create and region == creator_region
                roles_unit_path = f"../{creator_region}" if (create and not is_creator) else ""
                units.append({
                    "account_name": acct["name"],
                    "region": region,
                    "unit_name": f'{acct["name"]}-{region}',
                    "values": {
                        "account_name":        acct["name"],
                        "account_id":          account_id,
                        "region":              region,
                        # auth: aws_profile (static keys) OR deployer_role_arn (assume-role)
                        "aws_profile":         acct.get("aws_profile", ""),
                        "deployer_role_arn":   acct.get("deployer_role_arn", ""),
                        "unit_name":           f'{acct["name"]}-{region}',
                        # Create the global IAM roles only in the creator region;
                        # reference them (name-only) everywhere else.
                        "create_target_roles": is_creator,
                        "target_roles":        target_roles(roles, is_creator),
                        # Set on referencing regions → wait for the creator unit.
                        "roles_unit_path":     roles_unit_path,
                    },
                })

        out_dir = os.path.join(REPO, "live", env_name)
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "terragrunt.stack.hcl")
        header = (
            "# GENERATED by live/scripts/generate-stacks.py from inventory.yaml.\n"
            "# Do not edit by hand — edit inventory.yaml and re-run the generator.\n\n"
        )
        with open(out_path, "w") as f:
            f.write(header + "\n\n".join(render_unit(u) for u in units) + "\n")
        print(f"{env_name}: {len(units)} units -> {os.path.relpath(out_path, REPO)}")


if __name__ == "__main__":
    main()
